repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["-l", "120"]
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        name: Format Markdown files
        files: \.md$

      - id: prettier
        name: Format YAML files
        files: \.(yaml|yml)$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        name: Format C/C++ code
        files: \.(c|cpp|h|hpp|cc|cxx)$
        args: [--style=file]
